#  CCCCC   OOOOO  NNN   NN FFFFFFFFF  IIIII  GGGGGG
# CCC     OO   OO NNNN  NN FF          III  GGG
# CC      OO   OO NN NN NN FFFFFF      III  GGG GGGG
# CCC     OO   OO NN  NNNN FF          III  GGG  GGG
#  CCCCC   OOOOO  NN   NNN FF         IIIII  GGGGGG
BungeecordReport:

  #MySQL Settings
  MYSQL:
    Host: localhost #Change here the Host of the Database
    Port: 3306 #Dont Change this without you now what you do!
    Database: BungeeReport #Change here the Name of the Database
    User: BungeeReport #Change here the User of the Database
    Password: 123 #Change here the Password of the User